name: Build Flutter APK

on:
  push:
    branches:
      - main  # Ubah jika branch utama kamu bukan 'main'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.6'  # Sesuaikan dengan versi lokal kamu

      - name: Install dependencies
        run: flutter pub get

      - name: Clean previous builds
        run: flutter clean

      - name: Build APK (Release)
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
